services:
  semu-aluguel-penha-nginx:
    image: nginx:latest
    container_name: semu-aluguel-penha-nginx
    restart: unless-stopped
    hostname: semu-aluguel-penha-nginx
    domainname: ${APP_DOMAIN_NAME:-aluguel.semu.ma.gov.br}
    ports:
      - ${APP_PORT:-8001}:80
    volumes:
      - ./docker/vhost:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx/
      - ./:/var/www/html/
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=aluguel.semu.ma.gov.br
    depends_on:
      - semu-aluguel-penha-php
    networks:
      - semu-aluguel-penha

  semu-aluguel-penha-php:
    container_name: semu-aluguel-penha-php
    hostname: semu-aluguel-penha-php
    image: ati/semu-aluguel-penha-php:1.0
    restart: unless-stopped
    build:
        context: ./docker/
        dockerfile: Dockerfile
    environment:
      TZ: America/Fortaleza
      SERVICE_NAME: semu-aluguel-penha-php
      SERVICE_TAGS: production
    volumes:
      - ./:/var/www/html/
      - ./docker/etc/php.ini:/usr/local/etc/php/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - semu-aluguel-penha

networks:
  semu-aluguel-penha:
    # name: semu-aluguel-penha
    driver: bridge
